[package]
name = "ipc-rust"
version = "0.1.0"
edition = "2018"

[dependencies]
winapi = { version = "0.3", features = [
  "winbase",
  "fileapi",
  "handleapi",
  "namedpipeapi",
  "winnt"
] }
serde = "1.0"
serde_json = "1.0"
byteorder = "1.4.3"
